### ISSUE TITLE
Error in benchmark

### ISSUE THREAD

**Issue by reubenharry** [tweag/monad-bayes#131]
On running `stack bench`:

```
ssm-bench: Oops!  Entered absent arg $dMonad Monad (Population m)
"RM-SMC"
Benchmark ssm-bench: ERROR
Completed 2 action(s).
```

**Comment by turion** [comment]
I'm still encountering this issue reproduceably when trying to run the test suite with GHC 8.10.7:

```
Failures:

  test/Spec.hs:152:5: 
  1) Expectation from all inference methods gives correct answer for the sprinkler model
       uncaught exception: ErrorCall
       Oops!  Entered absent arg $dMonad Monad (Population m)

  To rerun use: --match "/Expectation from all inference methods/gives correct answer for the sprinkler model/"

Randomized with seed 1981298286
```

This seems to be a family of GHC bugs that reappear since over a decade:

https://gitlab.haskell.org/search?search=Oops!%20Entered%20absent%20arg&nav_source=navbar&project_id=1&group_id=2&scope=issues

I'm not sure, maybe we should simply drop 8.10 from the list of supported GHCs?
