### ISSUE TITLE
Why use Lists for streams in the lazy sampler?

### ISSUE THREAD

**Issue by turion** [tweag/monad-bayes#184]
Just a small nitpick. Wouldn't it be clearer to use a stream type in the definition of trees?

```
data Stream a = Stream a (Stream a)
data Tree = Tree Double (Stream Tree)
```

Otherwise, it is too easy to mistake the `Tree` for a [rose tree](https://en.wikipedia.org/wiki/Rose_tree).

If you're interested, I can send a PR for this.

**Comment by reubenharry** [comment]
That seems reasonable. Two things to note:
1. I copied the lazy sampler pretty much wholesale from [LazyPPL](https://lazyppl.bitbucket.io/) (with their permission). I was cautious to make changes I wasn't certain were semantics preserving, because I didn't fully understand how it worked. So if you're confident in the change, I'm definitely in favour and happy to review a PR
