### ISSUE TITLE
1.0.0 does not build on hackage

### ISSUE THREAD

**Issue by idontgetoutmuch** [tweag/monad-bayes#221]
@reubenharry can you take a look? https://hackage.haskell.org/package/monad-bayes-1.0.0/reports/1

**Comment by reubenharry** [comment]
Was the recent PR meant to fix this?

**Comment by vkleen** [comment]
I think this happens because `monad-bayes` is not specifying version bounds on `brick`. The 1.0 release of `brick` makes breaking changes to the `EventM` interface. Porting to this new version turns out to be pretty straightforward though; I've made PR #229 specifying `brick` versions between 1.0 and a future 2.0.

Alternatively, specifying a version upper bound of `<= 0.73` on `brick` should also work. I haven't tested that, though.

**Comment by idontgetoutmuch** [comment]
@reubenharry thanks for remembering to close this - the version on hackage now builds (thanks to @vkleen)
