### ISSUE TITLE
Examples for variational/hmc inference

### ISSUE THREAD

**Issue by reubenharry** [tweag/monad-bayes#40]
This library is really awesome, and I've been using it to implement some linguistic models recently (along the lines of http://gscontras.github.io/ESSLLI-2016/chapters/1-introduction.html). I'm having trouble getting the fancier inference methods to work (currently I'm just using enumerate and working with discrete variables), so was wondering if there were any simple examples of variational or hmc inference that I could try out, to get the hang of it.

**Comment by adscib** [comment]
Thanks for your feedback and great to hear you find the library useful! HMC and VI are a result of a somewhat experimental attempt to use automatic differentiation within monad-bayes but I found the resulting architecture to be too complicated so I'm not planning to maintain these algorithms in their current shape. Nonetheless, the implementations on `master` work so you should be able to use them.

The main point about these two algorithms is that they can only be applied to models where all random variables are continuous and their number is the same in every possible execution path. In particular if your model has discrete components you won't be able to use them. Are you generally familiar with MCMC or variational inference? To get good results from them you'll have to tune the parameters which requires some level of expertise - there are ways to do it automatically but since I'm not planning to support the current implementation I probably won't get around to implementing these.

If your model doesn't satisfy those requirements or you don't want to fiddle with parameters I would recommend that you go to the branch `simple` and try using that code instead. In particular it has a function `Control.Monad.Bayes.Traced.mh` which implements a lightweight Metropolis-Hastings variant that's not very powerful but doesn't require any tuning and should be very easy to use. It also works for all models, including ones with discrete variables. The content of `simple` branch will be supported so I'll get some examples for how to use it relatively soon.

**Comment by reubenharry** [comment]
Awesome, thanks so much for the tips! I'll try out Control.Monad.Bayes.Traced.mh. I'm currently working in Edward (using HMC and VI), but this seems like a really elegant alternative. (you can see a simple model I wrote using monad-bayes at https://reubenharry.github.io/posts/bayesian-pragmatics.html if you're curious).
